language: generic
os: osx

install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - curl --location --remote-name http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xf install-tl-unx.tar.gz
  - cd install-tl-20*
  - echo -e "selected_scheme scheme-minimal\nTEXDIR /usr/local/texlive\noption_doc 0\noption_src 0" > texlive.profile
  - sudo ./install-tl -no-gui -profile=texlive.profile
  - cd ..
  - PATH=$PATH:/usr/local/texlive/bin/x86_64-darwin
  # Asymptote requires Ghostscript. Also, creating MailChimp.png requires
  # converting a PDF to a PNG using ImageMagick convert, which also relies on
  # Ghostscript. After https://github.com/Homebrew/homebrew-core/pull/31558,
  # Homebrew’s ImageMagick didn’t permit using Ghostscript (due to security
  # vulnerabilities) unless the --with-ghostscript option of the imagemagick
  # formula was used, but this was relaxed with
  # https://github.com/Homebrew/homebrew-core/commit/16e1df6dc2657cae75996c15051139ed9a335ff6
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install ghostscript imagemagick
  - sudo tlmgr install
    asymptote
    fontspec
    latex-bin
    luaotfload
    luatex85
    oberdiek
    standalone
    xcolor
    xkeyval
  - curl --location --remote-name https://github.com/lcamichigan/cross-and-crescent/releases/download/v1.5/crossAndCrescent.asy

script:
  - make
