# https://www.appveyor.com/docs/appveyor-yml

install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - ps: Start-FileDownload 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
  - 7z x install-tl.zip
  - cd install-tl-20*
  # The install-tl-windows.bat script contains pause commands that stop
  # execution until a key is pressed. Remove these.
  - ps: Set-Content install-tl-windows.bat (Get-Content install-tl-windows.bat | Select-String -Pattern '^pause$' -NotMatch)
  - ps: Set-Content texlive.profile "selected_scheme scheme-minimal`nTEXDIR C:\texlive`noption_doc 0`noption_src 0`n"
  - install-tl-windows -no-gui -profile=texlive.profile
  - cd ..
  - set PATH=%PATH%;C:\texlive\bin\win32
  - tlmgr install asymptote
  - ps: Start-FileDownload 'https://github.com/lcamichigan/cross-and-crescent/releases/download/v1.4/crossAndCrescent.asy'
  - choco install imagemagick.tool

build_script:
  # Other Make executables are in C:\cygwin64\bin and C:\msys64\usr\bin.
  - C:\cygwin\bin\make
    Eventbrite.png
    Facebook.png
    GitHub.png
    LinkedIn.png
    Twitter.png
    WebsiteHeader.png
    Xero.png
  # ImageMagick’s convert.exe conflicts with C:\Windows\System32\convert.exe,
  # so don’t use the Makefile to create favicon.ico.
  - asy -outformat png -noView favicon.asy
  - C:\ProgramData\chocolatey\lib\imagemagick.tool\tools\convert favicon-16.png favicon-32.png favicon-64.png favicon-128.png favicon-256.png favicon.ico
  # Skip MailChimp.png, which requires a commercial font.

test: off

artifacts:
  - path: Eventbrite.png
  - path: Facebook.png
  - path: favicon.ico
  - path: GitHub.png
  - path: LinkedIn.png
  - path: Twitter.png
  - path: WebsiteHeader.png
  - path: Xero.png

skip_tags: true
